image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Install Rust
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source "$HOME/.cargo/env"
      # Install Solana
      sh -c "$(curl -sSfL https://release.solana.com/stable/install)" -y
      export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
      # Install Anchor
      cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked
      # Verify installations
      solana --version && anchor --version
